# Deployment 1: Default Behavior Overridden
apiVersion: v1
kind: Pod
metadata:
  name: nginx-default-command
spec:
  containers:
    - name: default-container
      image: ghcr.io/${{ github.repository }}:latest
      command: ["nginx"]
      args: ["-g", "daemon off;"]