# Deployment 2: Custom Command (Sleep)
apiVersion: v1
kind: Pod
metadata:
  name: custom-command-pod
spec:
  containers:
    - name: custom-container
      image: ghcr.io/jar3/run_commands_and_args_in_container:latest
      command: ["sleep"]
      args: ["3600"]